# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374c40cbf122671d1fe6eaef1643e91a268e315fcb2e16cf73395d2e46da240d3ed96c0e8affde06505339f247e450f2382035feece5a417f5d64488c35e0c9c

test:
  secret_key_base: e63d50932433e523b70f54658209a0e1c9d0d2de059cfbeb56eb2d88567db9269658a75363519f52a86a93963badba7a820aa03a3f0f9658d5e4d8e4cb45d8c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
